// Generated by CoffeeScript 2.7.0
import Fa from 'svelte-fa/src/fa.svelte';

import {
  faHouse,
  faCircleInfo,
  faCog
} from '@fortawesome/free-solid-svg-icons/index.js';

export var load = function() {
  return {
    sections: [
      {
        slug: '',
        title: 'Home',
        icon: faHouse
      },
      {
        slug: 'profile/',
        title: 'Profile',
        icon: faCog
      },
      {
        slug: 'about/',
        title: 'About',
        icon: faCircleInfo
      }
    ]
  };
};

export var csr = true;

export var ssr = true;

export var prerender = true;
