// Generated by CoffeeScript 2.7.0
import Fa from 'svelte-fa/src/fa.svelte';

import { faUser, faHouse, faCircleInfo, faCog } from '@fortawesome/free-solid-svg-icons/index.js';

export var load = function () {
	return {
		sections: [
			{
				slug: '',
				title: '',
				icon: faHouse
			},
			{
				slug: 'profile/',
				title: '',
				icon: faUser
			},
			{
				slug: 'settings/',
				title: '',
				icon: faCog
			},
			{
				slug: 'about/',
				title: '',
				icon: faCircleInfo
			}
		]
	};
};

export var csr = true;
export var ssr = false;
export var prerender = false;
